type Query {
   getUsers: [User!]!
   getUser(id: ID!): User
   self: User
}

type User {
   id: ID!
   name: String!
   joinedAt: String!
   email: String!
   image: String
   emailVerified: Boolean!
   seeded: Boolean
   settings: Settings!
}

type Settings {
   visibility: VisiblitySettings!
}

type VisiblitySettings {
   profile: Boolean!
   progress: Boolean!
   favourites: Boolean!
}
