type Query {
   getProgressesOf(user: ID!): [Progress!]!
   getOwnProgresses: [Progress!]!

   getProgressOf(show: Int!, user: ID!): Progress
   getOwnProgress(show: Int!): Progress
}

type Mutation {
   setWatched(show: Int!, episodes: [Int!]!): Progress!
}

type Progress {
   id: ID!
   userId: ID!
   showId: Int!
   show: Show!
   user: User!
   watched: [Int!]!
}
