fragment baseList on List {
   id
   name
   slug
   userId
}

query isFavourite($show: Int!) {
   isFavourite: isInList(show: $show, primary: true)
}

mutation addFavourite($shows: [Int!]!) {
   list: addToList(shows: $shows, primary: true) {
      id
   }
}

mutation removeFavourite($shows: [Int!]!) {
   list: removeFromList(shows: $shows, primary: true) {
      id
   }
}
