fragment baseProgress on Progress {
   id
   watched
   showId
   userId
}

fragment progressWithShow on Progress {
   ...baseProgress
   show {
      ...baseShow
   }
}

query progress($show: Int!) {
   progress: getProgress(show: $show) {
      ...baseProgress
   }
}

query progressWithShow($show: Int!) {
   progress: getProgress(show: $show) {
      ...baseProgress
      show {
         id
         name
         overview
      }
   }
}

query userProgresses($user: ID!) {
   progresses: progressesOf(user: $user) {
      ...baseProgress
      show {
         id
         name
      }
   }
}

mutation setWatched($show: Int!, $episodes: [Int!]!) {
   setWatched(show: $show, episodes: $episodes) {
      ...baseProgress
   }
}
