fragment baseShow on Show {
   id
   tvdb_id
   name
   overview
   image
}

fragment baseEpisode on Episode {
   id
   name
   aired
   runtime
   isMovie
   number
   seasonNumber
   special
   ignore
   due
   watched
}

fragment withEpisodes on Show {
   ...baseShow
   episodes {
      ...baseEpisode
   }
}

fragment showWithProgress on Show {
   ...baseShow
   isFavourite: isIn(primary: true)
   progress {
      ...baseProgress
   }
}

query show($id: Int!) {
   show: getShow(id: $id) {
      ...showWithProgress
   }
}

query search($by: String!) {
   results: searchShows(by: $by) {
      ...baseShow
   }
}
