fragment baseUser on User {
   id
   name
   joinedAt
   email
   settings {
      visibility {
         profile
         progress
         favourites
      }
   }
}

query user($id: ID!) {
   user: getUser(id: $id) {
      ...baseUser
   }
}

query users {
   users: getUsers {
      ...baseUser
   }
}

query self {
   user: self {
      ...baseUser
   }
}
