name: Build Full

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
    paths:
      - backend/**
      - frontend/**
      - Dockerfile

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Extract branch name
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: branch
        
      - name: Build Backend
        run: docker build backend --tag backend
      
      - name: Build Frontend
        run: docker build frontend --tag frontend

      - name: Build & Publish Container
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          image_name: ${{ secrets.DOCKER_USERNAME }}/gluttony
          image_tag: latest,full
          push_image_and_stages: ${{ steps.branch.outputs.branch == 'main' }}
